apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mnt/nfs-share/contacts-app/mdb
    server: 10.0.2.4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
status: {}
