services:

  contacts-web:
    image: sgconline/contacts-web:v2.0
    ports:
      - 80:80
    networks:
     - front-end
     - back-end
    depends_on: 
      - contacts-app
      
  contacts-app:
    image: sgconline/contacts-app:v2.0
    networks:
     - back-end
  depends_on: 
     - contacts-mdb

  contacts-mdb:
    image: sgconline/contacts-mdb:v2.0
    ports:
      - 27017:27017
    networks:
     - back-end
    depends_on: 
          - contacts-app
networks:
  front-end:
  back-end:
