apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-web
  labels:
    app: contacts-web
    tier: front-end

spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      name: contacts-web
      labels:
        tier: front-end

    spec:
      containers:
      - name: contacts-web
        image: sgconline/contacts-web:v1.1
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-web
spec:
  type: NodePort
  selector: 
    tier: front-end
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
