apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-web
  labels:
    app: contacts-web
    component: web

spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-web
      component: web
  template:
    metadata:
      name: contacts-web
      labels:
        app: contacts-web
        component: web

    spec:
      containers:
      - name: contacts-web
        image: sgconline/contacts-web:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-web
spec:
  type: NodePort
  selector: 
    app: contacts-web
    component: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
