--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-mdb
  namespace: contacts-app
  labels:
    app: contacts-mdb
    component: db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-mdb
      component: db
  template:
    metadata:
      name: contacts-mdb
      labels:
        app: contacts-mdb
        component: db

    spec:
      containers:
      - name: contacts-mdb
        image: sgconline/contacts-mdb:v2.2
        volumeMounts:
        - name: mdb-config
          mountPath: /tmp
      resources:
        requests:
          cpu: 1
          mem: 1m
      volumes:
      - name: mdb-config
        configMap:
          name: contacts-app-mdb-cm
          items:
          - key: docker-entrypoint-initdb.d
            path: docker-entrypoint-initdb.d

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
  namespace: contacts-app
  labels:
    app: contacts-app
    component: app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: contacts-app
      component: app
  template:
    metadata:
      name: contacts-app
      labels:
        app: contacts-app
        component: app

    spec:
      containers:
      - name: contacts-app
        image: sgconline/contacts-app:v2.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-web
  namespace: contacts-app
  labels:
    app: contacts-web
    component: web

spec:
  replicas: 3
  selector:
    matchLabels:
      app: contacts-web
      component: web
  template:
    metadata:
      name: contacts-web
      labels:
        app: contacts-web
        component: web

    spec:
      containers:
      - name: contacts-web
        image: sgconline/contacts-web:v2.2

---
apiVersion: v1
kind: Service
metadata:
  name: contacts-mdb
  namespace: contacts-app
spec:
  type: ClusterIP
  selector: 
    app: contacts-mdb
    component: db
  ports:
  - protocol: TCP
    port: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: contacts-mdb-adm
  namespace: contacts-app
spec:
  type: NodePort
  selector: 
    app: contacts-mdb
    component: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30017
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-app
  namespace: contacts-app
spec:
  type: ClusterIP
  selector: 
    app: contacts-app
    component: app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: contacts-web
  namespace: contacts-app
spec:
  type: NodePort
  selector: 
    app: contacts-web
    component: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
