apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-mdb
  labels:
    app: contacts-mdb
    component: db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-mdb
      component: db
  template:
    metadata:
      name: contacts-mdb
      labels:
        app: contacts-mdb
        component: db

    spec:
      containers:
      - name: contacts-mdb
        image: sgconline/contacts-mdb:v2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
  labels:
    app: contacts-app
    component: app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-app
      component: app
  template:
    metadata:
      name: contacts-app
      labels:
        app: contacts-app
        component: app

    spec:
      containers:
      - name: contacts-app
        image: sgconline/contacts-app:v2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-web
  labels:
    app: contacts-web
    component: web

spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-web
      component: web
  template:
    metadata:
      name: contacts-web
      labels:
        app: contacts-web
        component: web

    spec:
      containers:
      - name: contacts-web
        image: sgconline/contacts-web:v2.0

---
apiVersion: v1
kind: Service
metadata:
  name: contacts-mdb
spec:
  type: ClusterIP
  selector: 
    app: contacts-mdb
    component: db
  ports:
  - protocol: TCP
    port: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: contacts-app
spec:
  type: ClusterIP
  selector: 
    app: contacts-app
    component: app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: contacts-web
spec:
  type: NodePort
  selector: 
    app: contacts-web
    component: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
