apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: mongodb-pvc
  namespace: contacts-app

spec:
  storageClassName: nfs

  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 1Gi
