apiVersion: v1

kind: Pod

metadata:
  name: nfs-pod

spec:
  containers:
    - image: nginx
      name: nfs-client
      volumeMounts:
      - name: nfs-volume
        mountPath: /nfs-share
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc

