services:
  contacts-app:
    image: sgconline/contacts-app:v1.1
    networks:
     - front-end

  contacts-web:
    image: sgconline/contacts-web:v1.1
    ports:
      - 80:80
    networks:
     - front-end
     - back-end
    depends_on: 
      - contacts-app

networks:
  front-end:
  back-end:
