apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 
resources:
  - ./contacts-app-ns.yml
  - app/
  - mdb/
  - web/

patches:
  - target:
      kind: Deployment
    patch: |- 
      - op: add
        path: /metadata/namespace
        value: contacts-app
  - target:
      kind: Service
    patch: |- 
      - op: add
        path: /metadata/namespace
        value: contacts-app
  - target:
      kind: ConfigMap
    patch: |- 
      - op: add
        path: /metadata/namespace
        value: contacts-app
  - target:
      kind: Secret
    patch: |- 
      - op: add
        path: /metadata/namespace
        value: contacts-app
