---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
  labels:
    app: contacts-app
    component: app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-app
      component: app
  template:
    metadata:
      name: contacts-app
      labels:
        app: contacts-app
        component: app

    spec:
      serviceAccount: contacts-app-sa
      serviceAccountName: contacts-app-sa
      initContainers:
      - name: wait-for-mongodb
        image: busybox:latest
        env:
        - name: MONGODB_HOST
          value: "contacts-mdb"
        command: 
        - "/bin/sh"
        args:
        - "-c"
        - >
          until nc -z ${MONGODB_HOST} 27017;
          do echo "$(date) - Waiting for MongoDB ${MONGODB_HOST}..."; sleep 2; done;
      containers:
      - name: contacts-app
        image: sgconline/contacts-app:v2.0

