services:

  contacts-web:
    image: sgconline/contacts-web:v2.2
    ports:
      - 80:80
    networks:
     - front-end
     - back-end
    depends_on: 
      - contacts-app
      
  contacts-app:
    image: sgconline/contacts-app:v2.3
    ports:
      - 8000:8000
    networks:
     - back-end
    depends_on: 
     - contacts-mdb

  contacts-mdb:
    image: sgconline/contacts-mdb:v2.2
    ports:
     - 27017:27017
    networks:
     - back-end
networks:
  front-end:
  back-end:
