---
apiVersion: v1
kind: Service
metadata:
  name: contacts-app
  labels:
    app: contacts-app
    environment: qa
    component: svc
spec:
  type: ClusterIP
  selector: 
    app: contacts-app
    component: app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
