---
apiVersion: v1
kind: Service
metadata:
  name: contacts-web
  labels:
    app: contacts-app
    environment: dev
spec:
  type: NodePort
  selector: 
    app: contacts-web
    component: web
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009
