apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
  labels:
    app: contacts-app
    tier: back-end

spec:
  replicas: 3
  selector:
    matchLabels:
      tier: back-end
  template:
    metadata:
      name: contacts-app
      labels:
        tier: back-end

    spec:
      containers:
      - name: contacts-app
        image: sgconline/contacts-app:v1.1
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-app
spec:
  type: ClusterIP
  selector: 
    tier: back-end
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
