---
apiVersion: v1
kind: Service
metadata:
  name: contacts-web
  labels:
    app: contacts-app
    environment: prod
    component: svc
spec:
  type: ClusterIP
  selector: 
    app: contacts-app
    component: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
