---
apiVersion: v1
kind: Service
metadata:
  name: contacts-mdb
  labels:
    app: contacts-app
    environment: sandbox
spec:
  type: ClusterIP
  selector: 
    app: contacts-mdb
    component: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
