apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
  labels:
    app: contacts-app
    component: app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-app
      component: app
  template:
    metadata:
      name: contacts-app
      labels:
        app: contacts-app
        component: app

    spec:
      containers:
      - name: contacts-app
        image: sgconline/contacts-app:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-app
spec:
  type: ClusterIP
  selector: 
    app: contacts-app
    component: app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
