apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-mdb
  labels:
    app: contacts-mdb
    component: db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-mdb
      component: db
  template:
    metadata:
      name: contacts-mdb
      labels:
        app: contacts-mdb
        component: db

    spec:
      containers:
      - name: contacts-mdb
        image: sgconline/contacts-mdb:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-mdb
spec:
  type: ClusterIP
  selector: 
    app: contacts-mdb
    component: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
